services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: legal-strategist-api
    depends_on:
      - db
    restart: always
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      EMAIL_BLACKLIST: ${EMAIL_BLACKLIST:-""}
      EMAIL_WHITELIST: ${EMAIL_WHITELIST:-""}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RESPOND_EMAIL_WEBHOOK_URL: ${RESPOND_EMAIL_WEBHOOK_URL:-""}
      SEND_EMAIL_WEBHOOK_URL: ${SEND_EMAIL_WEBHOOK_URL:-""}
      DB_USERNAME: postgres
      DB_PASSWORD: titangroup123456
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: titangroup
      AWS_REGION: ${AWS_REGION:-""}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
      S3_BUCKET: ${S3_BUCKET:-""}
      TWO_CAPTCHA_KEY: ${TWO_CAPTCHA_KEY:-""}
      DEBUG_MODE: ${DEBUG_MODE:-false}
    ports:
      - "8100:8100"
  
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8100/v1
    container_name: legal-strategist-web
    restart: always
    ports:
      - "3002:3002"
  
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: titangroup123456
      POSTGRES_DB: titangroup
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
